# Generated by Django 4.0 on 2021-12-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number_of_seats',
            field=models.IntegerField(),
        ),
    ]
