# Generated by Django 4.0 on 2021-12-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_number_of_seats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarOwner',
            new_name='Owner',
        ),
    ]
